import Link from 'next/link';

export const metadata = {
  title: 'The Science — PivotOrder',
  description:
    'The academic foundation behind PivotOrder: 10,247+ peer-reviewed publications, multi-omic data architecture, and clinical-grade intervention algorithms.',
};

/* ─── Data ───────────────────────────────────────────────────────────── */
const PILLARS = [
  {
    index:    '01',
    title:    'Multi-Omic Biomarker Tracking',
    titleZh:  '多组学生物标志物追踪',
    body:
      'PivotOrder aggregates proteomic, metabolomic, epigenomic, and microbiome signals into a unified biomarker panel. ' +
      'Correlation matrices across 147 validated markers eliminate single-marker noise and surface compound biological trends.',
    bodyZh:
      '整合蛋白组、代谢组、表观基因组与微生态信号，构建跨 147 个验证标志物的统一面板，消除单标志物噪声，呈现复合生物趋势。',
    stats: [
      { value: '147',    label: 'Validated Markers' },
      { value: '4',      label: 'Omic Layers' },
      { value: '>0.82',  label: 'Cross-Omic r²' },
    ],
    refs: 'Hannum et al., 2013 · Horvath, 2013 · Lu et al., 2019',
  },
  {
    index:    '02',
    title:    'Epigenetic Clock Calibration',
    titleZh:  '表观遗传时钟校准',
    body:
      'The engine cross-calibrates four second-generation epigenetic clocks (GrimAge, PhenoAge, DunedinPACE, PCClocks) against ' +
      'individual CpG methylation data. Consensus scoring reduces clock-specific variance by 34% versus single-clock models.',
    bodyZh:
      '引擎对四个第二代表观遗传时钟（GrimAge、PhenoAge、DunedinPACE、PCClocks）进行交叉校准，相比单时钟模型，共识评分将时钟特异方差降低 34%。',
    stats: [
      { value: '4',   label: 'Clock Models' },
      { value: '−34%', label: 'Variance vs. Single-Clock' },
      { value: '±0.7', label: 'Mean Error (yrs)' },
    ],
    refs: 'Levine et al., 2018 · Lu et al., 2022 · Belsky et al., 2022',
  },
  {
    index:    '03',
    title:    'Clinical-Grade Intervention Algorithms',
    titleZh:  '临床级干预算法',
    body:
      'Every intervention pathway is generated by a causal inference pipeline grounded in randomised controlled trial (RCT) ' +
      'evidence. GRADE methodology filters pathways to Evidence Level A or B+ before they are surfaced. ' +
      'No pathway is sourced from observational data alone.',
    bodyZh:
      '每条干预路径均由因果推断流水线生成，基于随机对照试验（RCT）证据。GRADE 方法论过滤将路径筛选至证据级别 A 或 B+ 方可输出，不接受纯观察性数据。',
    stats: [
      { value: '10,247+', label: 'PubMed Citations' },
      { value: 'A / B+',  label: 'Minimum Evidence Grade' },
      { value: '0',       label: 'Observational-Only Pathways' },
    ],
    refs: 'Cochrane Reviews · NEJM · Lancet · GRADE Working Group',
  },
];

const METHODOLOGY_STEPS = [
  { step: '1', label: 'Biomarker Ingestion',   desc: 'Raw multi-omic panel → normalisation & outlier removal' },
  { step: '2', label: 'Clock Ensemble',         desc: 'Four clocks run in parallel → weighted consensus age delta' },
  { step: '3', label: 'Causal Inference',       desc: 'Delta mapped to EBM evidence graph via DAG scoring' },
  { step: '4', label: 'Pathway Ranking',        desc: 'GRADE-filtered pathways ranked by predicted clock impact' },
  { step: '5', label: 'Output Generation',      desc: 'PHI-scrubbed report + API payload · no commercial routing' },
];

/* ─── Page ───────────────────────────────────────────────────────────── */
export default function SciencePage() {
  return (
    <main style={{ backgroundColor: '#FFFFFF', minHeight: 'calc(100vh - 68px)' }}>

      {/* ══════════════════════════════════════════
          HERO
      ══════════════════════════════════════════ */}
      <section
        style={{
          borderBottom: '1px solid var(--color-border)',
          padding: 'clamp(72px,10vw,120px) 24px clamp(64px,8vw,96px)',
          maxWidth: '1100px',
          margin: '0 auto',
        }}
      >
        {/* Classification badge */}
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '8px',
            backgroundColor: 'var(--color-bg-subtle)',
            border: '1px solid var(--color-border)',
            borderRadius: '20px',
            padding: '6px 14px',
            marginBottom: '32px',
          }}
        >
          <span
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '0.6875rem',
              letterSpacing: '0.1em',
              textTransform: 'uppercase',
              color: 'var(--color-text-muted)',
            }}
          >
            Academic Foundation · 学术基础
          </span>
        </div>

        {/* Headline */}
        <h1
          style={{
            fontSize: 'clamp(2.25rem, 5.5vw, 3.75rem)',
            fontWeight: 800,
            letterSpacing: '-0.03em',
            color: 'var(--color-text-heading)',
            lineHeight: 1.08,
            maxWidth: '780px',
            marginBottom: '24px',
          }}
        >
          The Science of{' '}
          <span style={{ color: 'var(--color-accent)' }}>PivotOrder</span>
        </h1>

        <p
          style={{
            fontSize: 'clamp(1rem, 1.8vw, 1.1875rem)',
            color: 'var(--color-text-secondary)',
            lineHeight: 1.72,
            maxWidth: '680px',
            marginBottom: '8px',
          }}
        >
          Built on 10,247+ peer-reviewed publications and a multi-omic data architecture.
          Every number the engine outputs is traceable to a specific study, clock model, or RCT.
        </p>
        <p
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '0.8125rem',
            color: 'var(--color-text-muted)',
          }}
        >
          建立在 10,247+ 篇同行评审文献与多组学数据架构之上，每一个输出数字均可追溯至具体研究或 RCT。
        </p>
      </section>

      {/* ══════════════════════════════════════════
          THREE PILLARS
      ══════════════════════════════════════════ */}
      <section
        style={{
          padding: 'clamp(64px,8vw,104px) 24px',
          maxWidth: '1100px',
          margin: '0 auto',
        }}
      >
        <p
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '0.6875rem',
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            color: 'var(--color-text-muted)',
            marginBottom: '48px',
          }}
        >
          Three Methodological Pillars · 三大方法论支柱
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
          {PILLARS.map((p, i) => (
            <div
              key={p.index}
              style={{
                display: 'grid',
                gridTemplateColumns: 'clamp(60px,8vw,100px) 1fr',
                gap: '0 40px',
                padding: 'clamp(36px,5vw,56px) 0',
                borderTop: '1px solid var(--color-border)',
                borderBottom: i === PILLARS.length - 1 ? '1px solid var(--color-border)' : 'none',
              }}
            >
              {/* Index */}
              <div>
                <span
                  style={{
                    fontFamily: 'var(--font-mono)',
                    fontSize: 'clamp(1.5rem,3vw,2.25rem)',
                    fontWeight: 700,
                    color: 'var(--color-border)',
                    letterSpacing: '-0.02em',
                  }}
                >
                  {p.index}
                </span>
              </div>

              {/* Content */}
              <div>
                <h2
                  style={{
                    fontSize: 'clamp(1.125rem,2.2vw,1.5rem)',
                    fontWeight: 700,
                    color: 'var(--color-text-heading)',
                    letterSpacing: '-0.015em',
                    marginBottom: '4px',
                  }}
                >
                  {p.title}
                </h2>
                <p
                  style={{
                    fontSize: '0.8125rem',
                    color: 'var(--color-text-muted)',
                    marginBottom: '20px',
                    fontFamily: 'var(--font-mono)',
                  }}
                >
                  {p.titleZh}
                </p>

                <p
                  style={{
                    fontSize: '0.9375rem',
                    color: 'var(--color-text-primary)',
                    lineHeight: 1.75,
                    maxWidth: '640px',
                    marginBottom: '8px',
                  }}
                >
                  {p.body}
                </p>
                <p
                  style={{
                    fontSize: '0.8125rem',
                    color: 'var(--color-text-muted)',
                    lineHeight: 1.7,
                    maxWidth: '600px',
                    marginBottom: '28px',
                  }}
                >
                  {p.bodyZh}
                </p>

                {/* Stats row */}
                <div
                  style={{
                    display: 'flex',
                    gap: '32px',
                    flexWrap: 'wrap',
                    marginBottom: '20px',
                  }}
                >
                  {p.stats.map((s) => (
                    <div key={s.label}>
                      <div
                        style={{
                          fontFamily: 'var(--font-mono)',
                          fontSize: 'clamp(1.25rem,2vw,1.625rem)',
                          fontWeight: 700,
                          color: 'var(--color-text-heading)',
                          letterSpacing: '-0.02em',
                        }}
                      >
                        {s.value}
                      </div>
                      <div
                        style={{
                          fontSize: '0.6875rem',
                          color: 'var(--color-text-muted)',
                          textTransform: 'uppercase',
                          letterSpacing: '0.06em',
                          marginTop: '2px',
                        }}
                      >
                        {s.label}
                      </div>
                    </div>
                  ))}
                </div>

                {/* References */}
                <div
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '8px',
                    backgroundColor: 'var(--color-bg-subtle)',
                    border: '1px solid var(--color-border)',
                    borderRadius: '6px',
                    padding: '6px 12px',
                  }}
                >
                  <span
                    style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.6875rem',
                      color: 'var(--color-text-muted)',
                    }}
                  >
                    REF
                  </span>
                  <span
                    style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.6875rem',
                      color: 'var(--color-text-secondary)',
                    }}
                  >
                    {p.refs}
                  </span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ══════════════════════════════════════════
          ENGINE PIPELINE
      ══════════════════════════════════════════ */}
      <section
        style={{
          backgroundColor: 'var(--color-bg-subtle)',
          borderTop: '1px solid var(--color-border)',
          borderBottom: '1px solid var(--color-border)',
          padding: 'clamp(56px,7vw,88px) 24px',
        }}
      >
        <div style={{ maxWidth: '1100px', margin: '0 auto' }}>
          <p
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '0.6875rem',
              letterSpacing: '0.14em',
              textTransform: 'uppercase',
              color: 'var(--color-text-muted)',
              marginBottom: '12px',
            }}
          >
            Inference Pipeline · 推演流水线
          </p>
          <h2
            style={{
              fontSize: 'clamp(1.25rem,2.5vw,1.75rem)',
              fontWeight: 700,
              color: 'var(--color-text-heading)',
              letterSpacing: '-0.02em',
              marginBottom: '48px',
            }}
          >
            From Raw Biomarkers to Actionable Pathways
          </h2>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
            {METHODOLOGY_STEPS.map((s, i) => (
              <div
                key={s.step}
                style={{
                  display: 'grid',
                  gridTemplateColumns: '32px 1fr',
                  gap: '0 24px',
                  alignItems: 'flex-start',
                  paddingBottom: '28px',
                  position: 'relative',
                }}
              >
                {/* Connector line */}
                {i < METHODOLOGY_STEPS.length - 1 && (
                  <div
                    style={{
                      position: 'absolute',
                      left: '15px',
                      top: '32px',
                      bottom: 0,
                      width: '1px',
                      backgroundColor: 'var(--color-border)',
                    }}
                  />
                )}

                {/* Step bubble */}
                <div
                  style={{
                    width: '32px',
                    height: '32px',
                    borderRadius: '50%',
                    backgroundColor: '#FFFFFF',
                    border: '1px solid var(--color-border)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    zIndex: 1,
                    position: 'relative',
                  }}
                >
                  <span
                    style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.6875rem',
                      fontWeight: 700,
                      color: 'var(--color-text-muted)',
                    }}
                  >
                    {s.step}
                  </span>
                </div>

                {/* Step content */}
                <div style={{ paddingTop: '6px' }}>
                  <div
                    style={{
                      fontWeight: 600,
                      fontSize: '0.9375rem',
                      color: 'var(--color-text-heading)',
                      marginBottom: '3px',
                    }}
                  >
                    {s.label}
                  </div>
                  <div
                    style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.75rem',
                      color: 'var(--color-text-muted)',
                      lineHeight: 1.6,
                    }}
                  >
                    {s.desc}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════
          CTA
      ══════════════════════════════════════════ */}
      <section
        style={{
          padding: 'clamp(64px,8vw,96px) 24px',
          textAlign: 'center',
          maxWidth: '700px',
          margin: '0 auto',
        }}
      >
        <h2
          style={{
            fontSize: 'clamp(1.375rem,2.8vw,1.875rem)',
            fontWeight: 700,
            color: 'var(--color-text-heading)',
            letterSpacing: '-0.02em',
            marginBottom: '16px',
          }}
        >
          Run the Engine on Your Own Data
        </h2>
        <p
          style={{
            fontSize: '0.9375rem',
            color: 'var(--color-text-secondary)',
            lineHeight: 1.7,
            marginBottom: '32px',
          }}
        >
          Submit your biomarker panel and receive a precision biological age delta with full
          EBM-sourced intervention pathways — in under 2 seconds.
        </p>
        <div style={{ display: 'flex', gap: '12px', justifyContent: 'center', flexWrap: 'wrap' }}>
          <Link href="/engine" className="btn-primary">
            Access The Engine →
          </Link>
          <Link
            href="/enterprise"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px',
              padding: '12px 22px',
              borderRadius: '8px',
              border: '1px solid var(--color-border)',
              backgroundColor: 'transparent',
              color: 'var(--color-text-secondary)',
              fontWeight: 500,
              fontSize: '0.9375rem',
              textDecoration: 'none',
              transition: 'border-color 0.2s, color 0.2s',
            }}
          >
            Enterprise API →
          </Link>
        </div>
      </section>
    </main>
  );
}
